# Generated by Django 3.2.9 on 2021-11-20 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_urllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='url_redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='encurtador.urlredirect'),
        ),
    ]
