name: Python application

# Ativando CI no pull_request e push para branche princical:
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    # Configurando o postgres:
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testedb
        ports: [ '5432:5432' ]

    # Passos para build:
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev

    - name: Copying configurations
      run: |
        cp contrib/env-sample .env

    - name: Lint with flake8
      run: |
        pipenv run flake8 .

    - name: Test with pytest
      run: |
        pipenv run pytest devpro --cov=devpro

    - name: Posting Coverage
      run: |
        pipenv run codecov
